### ISSUE TITLE
The 'w' example on the github page is confusing

### ISSUE THREAD

**Issue by LeventErkok** [mikeizbicki/HerbiePlugin#10]
The example you use  `w far near` is very confusing! Does Herbie actually reorder the arguments? Because the improved version seems to say `w near far`.

From what I've seen trying Herbie on a few things, it only works at the expression level and wouldn't actually do this reordering. Making sure the very first example people see on Herbie actually repeatable would be much nicer!

**Comment by mikeizbicki** [comment]
Thanks.  This was a typo.  It's fixed now.
