### ISSUE TITLE
Produced expression is incorrect?

### ISSUE THREAD

**Issue by LeventErkok** [mikeizbicki/HerbiePlugin#11]
I've tried the following input, based on your example on the github page:

```
w :: Double -> Double -> Double
w far near = -(2 * far * near) / (far - near)
```

Running Herbie, I get the following output:

```
Compiling with Herbie floating point stabilization
Found math expression within binding w :: Double -> Double -> Double
  original expression = (2 * far * near) / (far - near)
  improved expression = if far < (negate 1.7210442634149447e81)
    then (far / (far - near)) * 2 * near
    else if far < 8.364504563556443e16
        then (far * 2) / (far - near) / near
        else (far / (far - near)) * 2 * near
  original error = 13.82279321294945 bits
  improved error = 2.34375e-2 bits
  WARNING: Not substituting the improved expression into your code
  WARNING: Cannot satisfy the constraint: Fractional Double
```

Based on this output, I created the following variant of `w`:

```
w' :: Double -> Double -> Double
w' far near = -(if far < (negate 1.7210442634149447e81)
    then (far / (far - near)) * 2 * near
    else if far < 8.364504563556443e16
        then (far * 2) / (far - near) / near
        else (far / (far - near)) * 2 * near)
```

Note that I put an extra negation around the Herbie suggested improvement, since it said the matched expression was without the negation in the original function `w`.

But these expressions wildly differ. Consider:

```
far, near :: Double
far = -1.4999999999999998
near = -1.25
```

We get:

```
ghci> w far near
15.000000000000012
ghci> w' far near
9.600000000000007
```

This is radically different output; and indeed if you do the "math" `w'` is way off. The correct result is much closer to what's computed by the original function `w`.

Am I reading Herbie's output incorrectly?

**Comment by LeventErkok** [comment]
Having taken another look at it, I think the expression in the second `then` should be:

```
((far * 2) / (far - near)) * near
```

instead of:

```
(far * 2) / (far - near) / near
```

That would make way more sense, but perhaps something else is going on here.

**Comment by mikeizbicki** [comment]
This related to issue #8.  I believe it's a parsing bug in the plugin code I wrote.  It'll probably be a few days before I get to take a look at this in more detail.

**Comment by mikeizbicki** [comment]
This should be fixed now.
