### ISSUE TITLE
standard numeric functions hypot and log1p and expm1

### ISSUE THREAD

**Issue by barak** [mikeizbicki/HerbiePlugin#12]
Some particular expressions are handled manually using standard numeric library functions in most languages. Three in particular are ```sqrt(x*x+y*y) = hypot(x,y)``` and ```log(1+x) = log1p(x)``` and ```expm1 x = exp x - 1```. Opportunities for ```hypot``` are ubiquitous in even casual numeric code, particularly in the form ```sqrt(1+x*x) = hypot(1,x)```.  Note that ```hypot``` is associative and commutative, and quite fast, so can be used with ```fold``` for computing the 2-norm of a vector. This would suggest the rewrite ```sqrt (sum (map (^2) xs)) = foldl hypot 0 xs```.

Unfortunately ```hypot``` and ```log1p``` and ```expm1``` are not in the standard preludes yet. But anyone who cares about numeric precision will probably be using them out of a library already.

**Comment by mikeizbicki** [comment]
The rewrite you suggest of `sqrt (sum (map (^2) xs)) = foldl hypot 0 xs` probably won't ever be supported by this plugin because higher order functions are extremely difficult to reason about.  But you make a good point about supporting `hypot`, `log1p`, and `expm1`.  These operations aren't currently supported by the Herbie program, so the plugin can't implement them.  I'll pass this suggestion along to the Herbie maintainers, though.  If/when they add these functions, I'll add them to the plugin.

**Comment by barak** [comment]
Yeah, I can see how ```foldl hypot``` is sort of outside the scope here. But I hope that ```sqrt(x^2+y^2) = hypot(x,y)``` can be put go on the queue.

**Comment by mikeizbicki** [comment]
I've left an issue with the herbie folks asking for this feature: https://github.com/uwplse/herbie/issues/73

**Comment by mikeizbicki** [comment]
HerbiePlugin now supports the `hypot`, `log1p`, and `expm1` functions.  By default, the standard Prelude does not have these functions in scope.  So if they are not in scope, the plugin disables the use of these functions and tries again.  So for example, given the function:

```
test1 :: Floating a => a -> a -> a
test1 a b = sqrt (a*a + b*b)
```

We get the output:

```
Found math expression within binding test1 :: forall a. Floating a => a -> a -> a
  original expression = sqrt ((a * a) + (b * b))
  improved expression = hypot a b
  original error = 29.88639024012792 bits
  improved error = 1.5625e-2 bits
  WARNING: Variable "hypot" not in scope
  WARNING: Disabling fancy numerical operations and retrying
  improved expression = if a < -1.1236950826599826e145
    then -a
    else if a < 1.116557621183362e93
        then sqrt ((a * a) + (b * b))
        else a
  original error = 29.88639024012792 bits
  improved error = 17.76095721289679 bits
  WARNING: Cannot satisfy the constraint Ord a
  WARNING: Disabling if statements and retrying
  Herbie could not improve the stability of the original expression
```
