### ISSUE TITLE
The 'w' example on the github page is wrong..

### ISSUE THREAD

**Issue by LeventErkok** [mikeizbicki/HerbiePlugin#13]
[This is related to #10, but github doesn't allow me to reopen closed tickets.]

The "improved" output given for `w` is wrong, same issue as in the ticket #11. (The division vs multiplication problem.)

Just keeping this ticket here so the very first example people see can be fixed when #11 is fixed as well!

**Comment by mikeizbicki** [comment]
Should be fixed now.  This was actually just an issue with me sucking at copy/pasting :(
