### ISSUE TITLE
w example is still wrong (only slightly)

### ISSUE THREAD

**Issue by LeventErkok** [mikeizbicki/HerbiePlugin#18]
[Sorry, I end up opening new tickets for the same thing. Github just doesn't allow opening closed tickets..]

There's just one issue left with the `w` example on the wiki-page. Note that Herbie recognizes the inner expression that is actually negated and optimizes it, so you need to wrap the modified code in a negate call.. 

I guess another way to look at this is why the plugin does *not* recognize the whole expression, but just the inner one. Perhaps it should directly recognize the top-level one and there's actually bug lurking in there.

**Comment by mikeizbicki** [comment]
I will be forever indebted to your excellent attention to detail :)

It should be fixed now.  The problem was that the plugin wasn't considering `negate` a math function.  I've added that to the functions considered and modified the pretty printer so that all calls to `negate` get displayed as `-`.
